import { global } from "./global.js";

let config = {
	expectedMaxSkillLevel: 9,
	screenshotMode: 0,
	borderChunk: 5,
	barChunk: 5,
	mininumBorderChunk: 3,
	darkBorders: 0,
	rgbBorders: false,
	noBorders: 0,
	colors: "classic",
	pointy: false,
	deathExpandRatio: true,
	fancyAnimations: true,
	resolutionScale: 1,
	fontSizeBoost: 10,
	fontStrokeRatio: 4.5,
	neon: 0,
	useFourRows: 1,
	disableMessages: 0,
	roundUpgrades: 0,
	drawOwnName: false,
	autoUpgrade: global.mobile,
	tintedDamage: true,
	lerpSize: true,
	glassMode: false,
	shaders: "Disabled",
	filterType: "none",
	tintedHealth: true,
	coloredHealthBars: false,
	memory: 60,
	newPrediction: 0,
	prediction: 2,
	fontFamily: "Ubuntu",
	localmotion: false,
};

export { config }