const global = {
	_selectedServer: 0,
	_windowSearch: {
		_server: "null",
		_lobby: "null",
		_party: "null",
	},
	mobile: /Android|webOS|iPhone|iPad|iPod|BlackBerry|android|mobi/i.test(navigator.userAgent),
	guiMouse: {
		x: 0,
		y: 0
	},
	_localmotion: {
		x: 0,
		y: 0,
		rx: 0,
		ry: 0,
	},
	_mapType: 0,
	_killTracker: 0,
	_forceTwiggle: false,
	KEY_ESC: 27,
	KEY_ENTER: 13,
	_canvas: null,
	KEY_CHAT: 13,
	KEY_FIREFOOD: 119,
	KEY_SPLIT: 32,
	KEY_LEFT: 65,
	KEY_UP: 87,
	KEY_RIGHT: 68,
	KEY_DOWN: 83,
	KEY_LEFT_ARROW: 37,
	KEY_UP_ARROW: 38,
	KEY_RIGHT_ARROW: 39,
	KEY_DOWN_ARROW: 40,
	KEY_AUTO_SPIN: 67,
	KEY_AUTO_FIRE: 69,
	KEY_OVER_RIDE: 82,
	KEY_UPGRADE_ATK: 49,
	KEY_UPGRADE_HTL: 50,
	KEY_UPGRADE_SPD: 51,
	KEY_UPGRADE_STR: 52,
	KEY_UPGRADE_PEN: 53,
	_diedAt: 0,
	KEY_UPGRADE_DAM: 54,
	KEY_UPGRADE_RLD: 55,
	KEY_UPGRADE_MOB: 56,
	KEY_UPGRADE_RGN: 57,
	KEY_UPGRADE_SHI: 48,
	KEY_MOUSE_0: 32,
	//KEY_MOUSE_1: 86,
	KEY_MOUSE_2: 16,
	KEY_LEVEL_UP: 78,
	KEY_TESTBED: 191,
	KEY_TESTBED_FIREFOX: 111,
	KEY_TESTBED_ALT: 192,
	KEY_RESET_BASIC_TANK: 80,
	KEY_CHANGE_TO_BASIC: 85,
	KEY_SUICIDE: 75,
	KEY_MAX_STATS: 77,
	KEY_GODMODE: 186,
	KEY_GODMODE_2: 59,
	KEY_COLOR_CHANGE: 66,
	KEY_SPAWN_SHAPES: 70,
	KEY_TELEPORT: 84,
	KEY_POWER_CYCLE: 222,
	KEY_POWER_CYCLE_FIREFOX: 165,
	KEY_BAN_PLAYER: 190,
	KEY_PASSIVE_MODE: 88,
	KEY_RAINBOW: 187,
	KEY_RAINBOW_2: 61,
	KEY_DEBUG: 76,
	KEY_CLASS_TREE: -69, //85, Disabled for now due to new mockup system
	KEY_TIER_SWITCH: 79,
	KEY_TIER_SWITCH_2: 81,
	KEY_OVERRIDE_ENTITY: 86,
	KEY_INFECT_MINION: 73,
	KEY_RESET_COLOR: 89,
	KEY_CONTROL_DOM: 72,
	KEY_TANK_JOURNEY: 220,
	KEY_KILL_WITH_MOUSE: 71,
	KEY_STEALTH: 74,
	KEY_DRAG: 90,
	DEV_KEY_1: 35,
	DEV_KEY_2: 40,
	DEV_KEY_3: 34,
	DEV_KEY_4: 37,
	DEV_KEY_5: 12,
	DEV_KEY_6: 49,
	DEV_KEY_7: 36,
	DEV_KEY_8: 38,
	DEV_KEY_9: 33,
	_screenWidth: 0,
	_screenHeight: 0,
	_gameWidth: 0,
	_gameHeight: 0,
	_gameStart: false,
	_disconnected: false,
	_died: false,
	_deathScreenState: 1, // 0 = on | 1 = off
	_loadingMockups: true,
	_debug: 1,
	_showTree: false,
	_scrollX: 0,
	_realScrollX: 0,
	_disconnectReason: "The connection was lost for an unknown reason.\nPlease press F12 or ctrl+shift+i then click on the console tab and take a screenshot, then send it in the discord.",
	_disableEnter: false,
	_seeInvisible: false,
	_tipSplash: [
		"Press the E key to enable autofire.",
		"Press the C key to enable autospin.",
		"Press the R key to disable drone and auto turret AI.",
		"Hold the N key to level up.",
		"Hold the Z key to change the color of the upgrade menu.",
		"Press the U key to show the class tree.",
		"Hold the M key and press a number stat to instantly max out that stat.",
		"Hold the L key to show extra debug stuff above the minimap.",
		"If you have a low frame rate, you can try enabling Low Graphics in the options menu, which removes death fade.",
		"Don't like seeing a lot of messages? Or maybe they cause you lag? Consider enabling the Disable Messages option.",
		"The Four Upgrade Rows option may make the upgrade menu look and fit on the screen better.",
		"Don't like the rounded edges look of Arras? Try the Use Miter Edges option.",
		"Begging for beta-tester on this server is like digging your own grave.",
		"Naming yourself Trans Rights makes your name have the colors of the Transgender Pride Flag.",
		"Don't get salty just because someone kills you; it's just a game, after all.",
		"Bosses are spawned by a randomizer; they may spawn every 8 to 15 minutes.",
		"The Password is 4NAX.",
		"The Password is Silvy.",
		"The password is SkuTsu.",
		"The Password is Trans Rights.",
		"Sanctuaries are spawned by a randomizer; they may spawn every 2 to 10 minutes.",
		"Sometimes, it helps to press Ctrl+R if your UI is bugged out.",
		"The first thing you should try if the client or in-game UI is bugged out is Ctrl+R.",
		"The first thing you should try if the client or in-game UI is bugged out is Ctrl+R.", // Duplicated on purpose // Jekyll - I might just automate this at some point /shrug
		"Sanctuaries can be seen on the minimap, and will spawn a boss when killed.",
		"Hitting the enemy deals more damage than not hitting them.",
		"If you can't take a joke, press Alt+F4 for godmode.",
		"Developers are marked by their badges next to their names.",
		"Developers typically have very fancy names.",
		'Import "Secret5"...',
		'Import "Pixel Mode"...',
		'Import "delete woomy"...',
		'Import "token"...',
		'Import "randomize"...'
	],
	_deathSplash: [
		"You are dead, not big surprise.",
		"All things must come to an end eventually.",
		"That's unfortunate...",
		"Your score was not in vain.",
		"Everyone falls to death; the destroyer of worlds.",
		"Tanks for playing!",
		"Don't be mad because you died; Be happy that you got the score you did.",
		"We interrupt this program to bring you this death screen.",
		"ZZAZZ Corruption will get to this world if you won't hurry and respawn!",
		"Success is not final, failure is not fatal: it is the courage to continue that counts.",
		"Dread it. Run from it. Destiny arrives all the same.",
		"F in the chat.",
		"Going to suggest a nerf again?",
		"Here lies your grave.",
		"Game over.",
		"Don't get mad, get even.",
		"Try, try again!",
		"OOF",
		"How much wood would a woodchuck chuck?",
		"Did you really think that through?",
		"Please refrain from abusing your computer.",
		"Ouch. Just ouch.",
		"Did you get a world record score?",
		"Try another tank, maybe it'll work out.",
		"Press Alt+F4 for godmode.",
		"L",
		"Cope",
		"Seethe",
		"Mald",
		"YO WE GOT THAT IN VIDEOOOOOOOO"
	],
	_deathSplashOverride: 0,
	_deathSplashChoice: 0,
	_tankMenuColor: 0,
	_tankMenuColorReal: 100 + Math.round(Math.random() * 70),
	searchName: "Basic",
	_arenaClosed: false,
	_ratio: window.devicePixelRatio,
	_fps: 60,
	_fpsc: 0,
	_fpscap: 1000 / 60,
	_oldFpsCap: 1000 / 60,
	_bandwidth: {
		_outbound: 0,
		_inbound: 0,
		_out: 0,
		_in: 0
	},
	_sentPackets: 80085,
	_receivedPackets: 80085,
	displayTextUI: {
		enabled: false,
		text: "",
		color: "#FFFFFF"
	},
	_waterAnimation: .5,
	_waterDirection: 1,
	_target: {
		_x: 0,
		_y: 0
	},
	_screenSize: Math.min(1920, Math.max(window.innerWidth, 1280)),
	_mobileOptions: false,
	_mobileFiring: [4, false],
	_mobileChatText: "Chat",
	_standalone: window.navigator.standalone || (window.matchMedia && window.matchMedia("(display-mode: fullscreen), (display-mode: standalone), (display-mode: minimal-ui)").matches),
}

export { global }