let map = {
    "MODE": "tdm",
    "ISSIEGE": true, 
    "serverName": "Boss Rush",//siege
    "TEAM_AMOUNT": 1,
    "MODE": "tdm",
    "WIDTH": 8000,
    "HEIGHT": 8000,
    "X_GRID": 30,
    "Y_GRID": 30,
    "MAX_FOOD": 20,
    "MAX_NEST_FOOD": 10,
    "MAX_CRASHERS": 30,
    "MAX_SANCS": 1,
    //"DO_BASE_DAMAGE": false,
    "ROOM_SETUP": [                                                                                     //mid
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","bas1","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","bas1","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"], //mid
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","bas1","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"], //what
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","bas1","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["bosp","bosp","bosp","bosp","bosp","bosp","bosp","bosp","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ],
    "BOTS": 25,
    "BORDER_FORCE": 0.025,
    "MAXBOSSES": 20,
    "MINBOSSES": 10,
    "CANNOT_SHOOT_IN_BASE": false
}
map